[project]
name = "py-advent-of-code"
version = "0.1.0"
description = "Python solutions for Advent of Code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
