#!/bin/bash

set -e

# Check if exactly two arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <year YYYY> <day DD>"
    exit 1
fi

# Assign arguments to variables
year=$1
day=$2
# Add leading zero to day if it's a single digit
day=$(printf "%02d" "$day")
year_day="${year}_${day}"

uv run -m "${year_day}.${year_day}"